### ISSUE TITLE
Some parts broke after latest update

### ISSUE THREAD

**Issue by foxnoodles** [Renset/lychee-flat-white-theme#1]
Namely sidebar and Top bar on main view are back to default dark theme.

**Comment by Renset** [comment]
Hey @foxnoodles, can you provide a bit more info, like screenshots, and Lychee version?

**Comment by foxnoodles** [comment]
As I mentioned in my post title it is the latest version of Lychee available at the moment of posting. So any newer version will also have the same issue. 

Just install the latest version and apply your theme. Better than any screenshot.

**Comment by Renset** [comment]
Fixed for Lychee v4.6.5
https://github.com/Renset/lychee-flat-white-theme/releases/tag/for-lychee-v4.6.5
