### ISSUE TITLE
button style

### ISSUE THREAD

**Issue by tinohager** [Renset/lychee-flat-white-theme#2]
Hi, thank you for the super theme

The Button style is different, it is easy possible to have the same style for all buttons?

![image](https://github.com/Renset/lychee-flat-white-theme/assets/8215186/a3c5a4fa-5ed7-44c6-b6fb-315ee5bfb6ef)
![image](https://github.com/Renset/lychee-flat-white-theme/assets/8215186/233f169d-ff65-45c7-8a42-a3144acfc11f)

**Comment by Renset** [comment]
Hi @tinohager, thanks for reporting this! 
I'll try fixing button styles soon

**Comment by Renset** [comment]
Fixed in v5
