### ISSUE TITLE
V5 styling

### ISSUE THREAD

**Issue by ildyria** [Renset/lychee-flat-white-theme#3]
Hi,

This is a heads up that your theme may no longer be working.
However with the integration of tailwind, it should be easier for you to design a new one.

This file should give you a nice head start on which properties to modify. :)
https://github.com/LycheeOrg/Lychee/blob/master/resources/css/app.css

**Comment by tinohager** [comment]
I can confirm that the current version no longer works.

**Comment by Renset** [comment]
Thank you guys, I will take this task soon :)

**Comment by tinohager** [comment]
maybe a basis to start with am not really familiar with tailwind 

![image](https://github.com/Renset/lychee-flat-white-theme/assets/8215186/1a830ed5-343c-430b-8f13-06e6abdbde2f)


```
:root {

  --text-main-0: #111111 !important;
  --text-main-100: #000000 !important;
  --text-main-200: #222222 !important;
  --text-main-400: #111111 !important;

  --bg-100: #ffffff !important;
  --bg-200: #ffffff !important;
  --bg-300: #ffffff !important;
  --bg-400: #ffffff !important;
  --bg-500: #ffffff !important;
  --bg-600: #ffffff !important;
  --bg-700: #eeeeee !important;
  --bg-800: #ffffff !important;
  --bg-900: #ffffff !important;
  --bg-950: #ffffff !important;
}

.basicModal__button {
  background-color:#dddddd;
  margin: 2px;
}

input[type=text] {
  border: 1px solid #ddd !important;
  border-radius: 5px;
  padding: 12px !important;
  height: 50px !important;
}

input[type=password] {
  border: 1px solid #ddd !important;
  border-radius: 5px;
  padding: 12px !important;
  height: 50px !important;
}

.text-neutral-200 {
  color: #333333 !important;
}

.fill-white {
  fill: #333333 !important;
}
```

**Comment by ildyria** [comment]
@tinohager  if you find some elements hard to style please do ping me. I'm sure we can make it easier for users. :)

The amount of code needed to change to lighter theme seems to already have made quite a big step forward in slimming down. :)

**Comment by tinohager** [comment]
```
:root {

  --text-main-0: #111111 !important;
  --text-main-100: #000000 !important;
  --text-main-200: #222222 !important;
  --text-main-400: #111111 !important;

  --bg-100: #ffffff !important;
  --bg-200: #ffffff !important;
  --bg-300: #ffffff !important;
  --bg-400: #ffffff !important;
  --bg-500: #ffffff !important;
  --bg-600: #ffffff !important;
  --bg-700: #eeeeee !important;
  --bg-800: #ffffff !important;
  --bg-900: #ffffff !important;
  --bg-950: #ffffff !important;
}

.basicModal__button {
  background-color:#dddddd;
  margin: 2px;
}

input[type=text] {
  background-color: #fefefe !important;
  border: 1px solid #ddd !important;
  border-radius: 5px;
  padding: 12px !important;
  height: 50px !important;
}

input[type=password] {
  background-color: #fefefe !important;
  border: 1px solid #ddd !important;
  border-radius: 5px;
  padding: 12px !important;
  height: 50px !important;
}

textarea {
  background-color: #fefefe !important;
  border: 1px solid #ddd !important;
  border-radius: 5px;
}

select {
  background-color: #fefefe !important;
  border: 1px solid #ddd !important;
  border-radius: 5px;
  padding: 10px !important;
  width: 100% !important;
  font-size: 14px !important;
}

.settings_view *:after {
  content: none !important;
}

.slider {
  background-color: #fefefe !important;
}

input:checked+.slider:before {
  background-color: var(--primary-500) !important;
}

.text-neutral-200 {
  color: #333333 !important;
}

.bg-neutral-800 {
  background-color: #fefefe !important;
}

.fill-white {
  fill: #333333 !important;
}

.overlay .text-text-main-0 {
  color: #ffffff !important;
}
```

**Comment by tinohager** [comment]
@ildyria It would be nice if you could address the field descriptions with a separate CSS class

![image](https://github.com/Renset/lychee-flat-white-theme/assets/8215186/7b8c9c3e-b05f-41e2-8efe-fcb44754e539)

![image](https://github.com/Renset/lychee-flat-white-theme/assets/8215186/33906092-5a6f-4ad4-a7de-da274c26510b)

![image](https://github.com/Renset/lychee-flat-white-theme/assets/8215186/7350c035-d636-49e1-8368-4570835103ab)



![image](https://github.com/Renset/lychee-flat-white-theme/assets/8215186/d9d6aca3-7bd4-439e-b685-9859a81a4818)
It would also be great if the textarea would not lose its size when saving. I drag it larger at the bottom right and it resets itself again and again

**Comment by tinohager** [comment]
@ildyria it is possible to add an extra css class if the `no_images.svg` is used? 
then we could invert the color of the image via css...

```
.thumbimg  {
  filter: invert(1);
}
```

**Comment by Renset** [comment]
@tinohager thanks for your findings and sharing! I was finally able to upgrade to v5, and planning to rebuild light theme this week (thanks to the holidays :). I'll post updates in this thread

**Comment by ildyria** [comment]
@tinohager 
```
    <img alt='Photo thumbnail'
		class='w-full h-full m-0 p-0 border-0 lazyload'
	src='https://lychee.test/img/no_images.svg'
	data-src='https://lychee.test/uploads-bck/thumb/331b2e2ed3f1ee959886060ec454cf84.jpeg'
	data-srcset='https://lychee.test/uploads-bck/thumb/331b2e2ed3f1ee959886060ec454cf84@2x.jpeg 2x'
    data-overlay='false'
    draggable='false' />
```

Maybe using a css selector for when data-src is not present would do a better trick ? 
We use the `no_images.svg` pretty much by default.

https://developer.mozilla.org/en-US/docs/Web/CSS/:not
https://stackoverflow.com/questions/7166259/is-there-a-css-selector-for-elements-lacking-an-attribute

So I guess something like:
```
.thumbimg img:not([data-src]) {
  filter: invert(1);
}
```

**Comment by Renset** [comment]
I decided to rewrite theme for [v5](https://github.com/Renset/lychee-flat-white-theme/tree/v5) from scratch based on your comments above, thanks @ildyria @tinohager. 
Still needs some polishing and deeper testing, but looks already usable.

![CleanShot 2024-01-05 at 00 47 28@2x](https://github.com/Renset/lychee-flat-white-theme/assets/364877/32f7cfa7-7ee2-44e3-b97d-c098eb424549)

![CleanShot 2024-01-05 at 00 47 56@2x](https://github.com/Renset/lychee-flat-white-theme/assets/364877/23ed6b91-c1c9-418f-b9b4-46d76ba925cf)

**Comment by ildyria** [comment]
@Renset if you open a PR between your v5 and your main, I will then be able create some comments and give you some feedback.

I will try to find those two and get rid of them to use `text-text-main-xxx` instead.
```css
.text-neutral-200 {
    color: var(--text-main-0) !important;
}

.text-neutral-300 {
    color: var(--text-main-0) !important;
}
```

This unless I am wrong, the second line is redundant because `bg-black` is in it. :thinking: 
```css
.bg-black,
div.absolute.top-0.left-0.w-full.h-full.bg-black.flex.items-center.justify-center.overflow-hidden {
    background: none !important;
}
```
Also because we are using [tailwindcss](https://tailwindcss.com/) I would avoid using selectors such as this kind of string `top-0.left-0.w-full.h-full.bg-black.flex` as we can change them a lot and they can be changed on the fly using AlpineJS/Livewire. I think it would be better to tell us which place you are trying to select for that and we can give you a css marker or html id for it, making it easier to customize.

**Comment by ildyria** [comment]
`.text-neutral-xxx` are a goner: https://github.com/LycheeOrg/Lychee/pull/2171

**Comment by Renset** [comment]
@ildyria `div.absolute.top-0.left-0.w-full.h-full.bg-black.flex.items-center.justify-center.overflow-hidden` was a quick fix as .bg-black override didn't work during tests. I'll look for more steady and specific selector. 
Thanks for the suggestion with PR, I'll create one when finish polishing work on the first version in v5 branch
